springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
spring:
  datasource:
    url: jdbc:postgresql://6.tcp.eu.ngrok.io:19096/postgres?currentSchema=nechto
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
